project:
  type: default
  output-dir: ../docs
  render:
    - integration.qmd
    - blog.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
  pdf:
    documentclass: scrreprt
    papersize: a4
    fontsize: 11pt
    number-sections: true
    include-in-header:
      text: |
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{pgfpages}
        \pgfpagesuselayout{2 on 1}[a4paper,landscape]
